# pull official base image
FROM node:20.13.1-alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
# COPY yarn.lock ./

# RUN yarn install --immutable 
RUN npm install
# add app
COPY . ./

# start app
CMD ["npm", "start"]
