version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://db:27017/uao_Yamamoto
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/event

  db:
    image: mongo
    volumes:
      - ./db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=uao_Yamamoto
    ports:
      - "27017:27017"
