version: '3'
services:
  backend:
    image: node:16.20.2
    container_name: my-mern-backend
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/uao_Yamamoto
    ports:
      - "5000:5000"  # Expose backend API on port 5000
    command: npm start

  frontend:
    image: node:16.20.2
    container_name: my-mern-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8080:3000"  # Expose frontend on port 8080
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/  # Set frontend API URL
    command: npm start
